import re, random
#from unidecode import unidecode

def remove_non_ascii(text):
    return unidecode(unicode(text, encoding = "utf-8"))

#Hello and Goodby
hellos = ["Hi!", "Hey!", "Yo!","Hey lovely!", "Bonjour.", "Salutations!", "Good day!", "Howdy stranger!", "Hey Friend."]
byes = ["Bye.", 'Later gator', 'Ciao mouse.', 'Seeya friend.', 'Till next time then.', "May we meet again in heaven or hell."]


#Filler words are discourse markers
fillers = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "Like, ", "Well, ", "Ok. ", "Gotcha. ", "Makes sense. ", "Yup, got it.  ", "Allrighty, ", "Anyway, ", "like, ", "Right. ", "So you know, ", "Fine - ", "Now ", "So... ", "Good! ", "Oh!  Ok. ", "Well... ", "It makes me think... ", "Great - ", "Okay - "]
filler_weights = [0.6, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02 ]

#Introductory statements
intros = [
"How are you feeling today - I want to go deep?",
    "What's going on - let's be real?",
    "I go deep.  What're you tiddly diddly doing?",
    "Life is a blessing.  How goes your path this holy day?",
    "Beyond the superficial... what's up?",
    "Tell me what is on your mind!  Let's get personal.",
#Bring up a memorable moment or anecdote your family or friends remember, such as a funny story, an embarrassing mishap, or a trip everyone enjoyed. This starter initiates multiple conversations about similar moments
    "How are ya doing right now?",
    "How's ya day been so far?",
    "How are you?",
    "How's your week been?",
    "What's happened for you today?",
    "How'd you sleep last night?",
    "I love this place because it's got great energy.",
    "Where are you from?",
    "I love your style!",
    "You look like a hard worker on things?",
    "You seem like a kind person. I like that.",
    "You look like a outgoing person!",
    "What do you have planned for the weekend?",
    "What's happening for you Friday?",
    "What's on your calendar this week?",
    "What's one thing you're really thankful for?",
    "What's something I don't know about you that you think I should know? Like... are you a stalker?",
    "What's one thing that's new in your life?",
    "What's recently changed in your life?",
    "What do you most admire about our country?",
    "What's one thing you've wanted to tell me, but haven't?",
    "I like how you smile when I come home from work.",
    "In your dream house, what one room must you have?",
    "What's a memory between us that stands out for you?",
    "If you happen to leave Earth before I do, how would you like me to remember you?",
    "What's one defining moment of your life so far?",
    "What's one thing you most want to do?",
    "What three words best describe you?",
    "What's something your friends don't even know about you?",
    "Ignoring your criminal history, what's the baddest thing you've done?",
    "What's the dumbest thing you've ever done?",
    "What was the best thing before sliced bread?",
    "In an emergency, why do you have to break glass to get a hammer to break glass?",
    "Can crop circles be square?",
    "Are you a person who does their duty or forges their own path?",
    "I've been asking a few people this and want your opinion because you seem like an intelligent person: is it more important to be respected or loved?",
    "What were the highs and lows of your day, today?",
    "What's something you regret?",
    "What one thing would you change in your life at the moment?",
    "If you could go back in time, what one thing would you change?",
    "What gives you the greatest joy in life?",
    "What makes you the happiest?",
    "If you're about to die, what do you need to have done to be fulfilled?",
    "What's hot in your life at the moment?",
    "What do you do for fun?",
    "What have you been doing in your time off recently?",
    "What's the first thing you notice about a person?",
    "In your opinion, what makes a good first impression?",
    "If you wrote a book, what would it be about?",
    "I wonder what your DJ name would be?",
    "What's the last thing you purchased online?",
    "What movies have you seen lately?",
    "What's on your music playlist at the moment?",
    "Watched any good shows recently?",
    "What book are you currently reading?"
]



#Transitions for volleys
change_topics = [
    "OK, changing the topic to your ",
    "I want to talk about your ",
    "Let's switch over to your ",
    "Something I was wondering about: your ",
    "So, I was thinking, can we discuss your "

]

#example of a native Python graph
graph_example = { "a" : ["c"],
          "b" : ["c", "e"],
          "c" : ["a", "b", "d", "e"],
          "d" : ["c"],
          "e" : ["c", "b"],
          "f" : [],
          "g" : []
        }

#Main volley topics, called life questions.  Need at least 10 per topic, each question should link to 4 others min
#How this works: first letter is key for graph, then the first value item is question, then the second item
#is a list of other graph points/keys that the question could connect to
life_questions = {
    "family":
        {"a":["Who in your family do you now care the most about?", ["c", "e", "h", "j", "k", "l"]],
        "b":["What is the most vivid memory you have of your parents?", ["b", "c", "d", "e", "h", "i", "j", "k", "l", "m"]],
        "c":["What did your family do for fun when you were a child?", ["b", "c", "d", "e", "f", "g","h", "i", "j", "k", "l", "m"]],
        "d":["Who was the most important adult in your life growing up?", [ "c", "d", "e",  "g","h", "i", "j", "l", "m"]],
        "e":["What are your mom's pet peeves, or your dad's?", [ "c", "d", "e", "f", "g","h", "i", "j", "k", "l", "m"]],
        "f":["Whom do you love most in your family?", ["d","g","h", "i", "j", "k"]],
        "g":["Did you have a family pet you loved, and what was their story?", [ "b",  "d", "f", "h", "j", "k"]],
        "h":["Who in your family did you have the hardest time with?", ["b", "c", "d", "e", "f", "g", "i", "j", "k", "l", "m"]],
        "i":["What got you out of bed as a kid?", ["b", "c", "f", "g", "j", "k"]],
        "j":["Who protected you as a child?", [ "f", "g","h", "i",  "k", "l", "m"]],
        "k":["Could you tell me a story or any memory of your brothers and sisters?", [ "c", "d", "f", "h", "i", "j"]],
        "l":["If there was one thing you'd want your kin and children to know about your family, what would it be?", [ "d", "f", "g","h", "i",  "k", "l", "m"]],
        "m":["What was the worst thing that happened to your family growing up?", [ "d", "f", "g","h", "i",  "k", "l", "m"]]
         },

    "religion":
        {"a":["What religion were your parents?", ["b","c", "d", "e", "f", "h", "i", "j", "k"]],
        "b":["What religion did most of your neighbors or community practice?", ["b", "c", "d", "e", "f", "h", "i", "j", "k"]],
        "c":["Did you grow up believing in God?", ["b", "c", "d", "e", "f", "g","h", "i", "j", "k"]],
        "d":["Were ethics or morals built into your childhood", [ "b", "c", "d", "e", "f", "g","h", "i", "j", "k"]],
        "e":["Do you think God runs the world - why or why not?", [ "b", "c", "d", "e", "f", "g","h", "i", "j", "k"]],
        "f":["Are you an atheist?", ["e", "f", "g","h", "i", "j", "k"]],
        "g":["What do you think of religious people who do bad things?", [ "b", "c", "d", "e", "f", "g","h", "j", "k"]],
        "h":["What do you think of religious people who do really kind and generous things?", ["b", "c", "d", "e", "f", "g","h", "i", "j", "k"]],
        "i":["What scared you about angels or demons as a child?", ["f", "g","h", "i", "j", "k"]],
        "j":["Who gave you your faith?", ["d", "e", "f", "g","h", "i", "j", "k"]],
        "k":["Do you have any spiritual or religious beliefs you want to pass on?", ["c", "d", "e", "f", "g","h", "i", "j", "k"]]
         },
    "school":
        {"a":["How did you like school?", ["c", "d", "e", "f", "h", "i", "j", "k"]],
        "b":["Where was school and what did you do there?", ["b", "c", "d", "e", "f", "h", "i", "j", "k"]],
        "c":["What were your schools like?", ["b", "c", "d", "e", "f", "g","h", "i", "j", "k"]],
        "d":["What was your favorite subject in school and why?", ["b", "c", "d", "e", "f", "h", "i", "j", "k"]],
        "e":["What subject in school was the easiest for you?", ["b", "c", "d", "e", "f", "h", "i", "j", "k"]],
        "f":["What was your least favorite subject in school and why?", ["b", "c", "d", "e", "f", "h", "i", "j", "k"]],
        "g":["Who was your favorite teacher and why was he/she special?", ["b", "c", "d", "e", "f", "h", "i", "j", "h"]],
        "h":["How do your fellow classmates from school remember you best?", ["b", "c", "d", "e", "f", "h", "i", "j", "k"]],
        "i":["What school activities and sports did you participate in?", ["b", "c", "d", "e", "h", "i", "j", "k"]],
        "j":["Did you and your friends have a special hangout where you liked to spend time?", ["b", "c", "d", "e", "f", "h", "i", "j", "k"]],
        "k":["Were you ever given any special awards for your studies or school activities?", ["b", "c", "d", "e", "f", "h", "i", "j", "k"]],
        "l":["How many years of education have you completed?", ["b", "c", "d", "e", "f", "p"]],
        "m":["Describe yourself as a young adult.", [ "f", "h", "i", "j", "k"]],
        "n":["Did you attend any school or training after high school - what did you study?", ["d", "e", "f", "h", "i", "j", "k"]],
        "o":["Do you have a college degree(s)?", ["g", "h", "l", "m"]],
        "p":["Did you get good grades?", ["f", "h", "i", "j", "k"]]
    },
    "home":
        {"a":["Where was your first home?", ["c", "d", "e", "f", "h", "i", "k"]],
        "b":["What were your earliest memories of your home?", ["c", "d", "e", "f", "h", "i", "k"]],
        "c":["Were there any fads during your childhood that you remember vividly?", ["b", "c", "d", "e", "f", "g","h", "i", "k"]],
        "d":["Was there a chore you really hated doing as a child?", [ "b", "c", "d", "e", "f", "g","h", "i",  "k"]],
        "e":["What books did you grow up with and love?", [ "c", "d", "e", "f", "g","h", "i", "k"]],
        "f":["Do you remember having a favorite song, cartoon, or TV show growing up?", ["d", "e", "f", "g","h", "i", "k"]],
        "g":["What games did you play the most growing up?", [ "c", "d", "e", "f", "g","h", "k"]],
        "h":["Were there any hard times, like when you didn't have enough food, money, or clothes?", ["e", "f", "g","h", "i", "j", "k"]],
        "i":["What was your most difficult memory growing up?", [ "f", "g","h", "i", "j", "k"]],
        "j":["Did anyone take advantage of you when you were a child?", [ "d", "e", "f", "g","h", "i", "j", "k"]],
        "k":["If there was one thing you could change about your home life growing up, what would it be?", [ "e", "f", "g","h", "i", "j", "k"]]
         },
    "job":
        {"a": ["As a child, what did you want to be when you grew up?", ["c", "d", "e", "f", "h", "i", "j", "k"]],
         "b": ["What were your jobs as a kid, if you had any?", ["b", "c", "d", "e", "f", "h", "i", "j", "k"]],
         "c": ["Tell me about all the jobs you've had!",
               [ "c", "d", "e", "f", "g", "h", "i", "j", "k"]],
         "d": ["What was your first real job?", ["c", "d", "e", "f", "g", "h", "i", "j", "k"]],
         "e": ["Did you ever have a really difficult or challening job - what was it like?", ["b", "c", "d", "e", "f", "g", "h", "i", "j", "k"]],
         "f": ["What have you learned about a work ethic and reliability along the way?", ["d", "e", "f", "g", "h", "i", "j", "k"]],
         "g": ["What job do you wish everyone should experience?", ["d", "e", "f", "g", "h", "j", "k"]],
         "h": ["Was there a career you ever got on?", [ "e", "f", "g", "h", "i", "j", "k"]],
         "i": ["What job advice would you give young people today?", ["b", "c", "d", "e", "f", "g", "h", "i", "j", "k"]],
         "j": ["Did you ever see someone badly hurt at work?", [ "h", "i", "e", "k"]],
         "k": ["Who do you know that has the best job in the world, and what is it?", [ "e", "f", "g", "h", "i", "j", "k"]],
        "l": ["Did you ever make enough money to live comfortably?", [ "g", "h", "i", "j", "k"]]
         },

    "partners":
        {"a": ["How old were you when you started dating?", ["c", "d", "e", "aa" ]],
        "aa": ["Do you remember your first crush - who was it?", ["ab"]],
        "ab": ["How old were you again, and what exactly happened?", ["c", "d", "e", ]],
         "b": ["Do you remember the first person you ever loved - who was it and describe them?", ["b", "c", "d", "e"]],
         "c": ["Can you tell me who your last 2 lovers were?",
               ["f", "g", "h", "i", "j", "k"]],
         "d": ["Did you ever want to get married in your life?", [ "e", "f", "g", "h", "i", "j", "k"]],
         "e": ["Do you have a spouse now?  If you do, can you tell me about your wedding proposal or first date?", ["e", "f", "g", "h", "i", "j", "k"]],
         "f": ["What did your learn from your parents about dating or marriage?", ["b", "c", "d", "e", "f", "g", "h", "i", "j", "k"]],
         "g": ["From your own experience or watching others, what advice would you give about long term relationships or marriage?", ["b", "c", "d", "e", "f", "g", "h", "j", "k"]],
         "h": ["Who are the happiest married people you know, and why?", [ "g", "h", "i", "j", "k"]],
         "i": ["Why do you think people get divorced?", [ "f", "g", "h", "i", "j", "k"]],
         "j": ["If you were single now and had to marry a close friend, who would it be?", [ "g", "h", "i", "j", "k"]],
         "k": ["Is marriage even worth it?", ["e", "f", "g", "h", "i", "j", "k"]]
         },


    "health":
        {"a": ["What do you do regularly for exercise?", ["c", "d", "e", "f", "h", "i", "j", "k"]],
         "b": ["Did you have any of the childhood diseases or major problems?", ["b", "c", "d", "e", "f", "h", "i", "j", "k"]],
         "c": ["Did your parents have any major health issues?",
               ["b", "c", "d", "e", "f", "g", "h", "i", "j", "k"]],
         "d": ["Do you have any bad habits now or in the past?", ["b", "c", "d", "e", "f", "g", "h", "i", "j", "k"]],
         "e": ["Have you ever been in a serious accident?", ["b", "c", "d", "e", "f", "g", "h", "i", "j", "k"]],
         "f": ["Have you ever been nearly dead - tell me about it?", ["b", "c", "d", "e", "f", "g", "h", "i", "j", "k"]],
         "g": ["Has anyone ever saved your life?", [ "g", "h", "j", "k"]],
         "h": ["What have you learned about staying healthy or getting sick?", ["c", "d", "g", "h", "i", "j", "k"]],
         "i": ["Do you have any health or eating or exercise advice for others?", ["h", "i", "j", "k"]],
         "j": ["Any major health issues you'd like to share?", ["d", "e", "f", "g", "h", "i", "j", "k"]],
         "k": ["Who is the healthiest person you know, and why?", ["b", "c", "d", "e", "f", "g", "h", "i", "j", "k"]]
         },

    "history":
        {"a": ["What do you think was the most important historical event in your life?", ["c", "d", "e", "f", "h", "i", "j", "k"]],
         "b": ["Do you remember your family discussing world events and politics?", ["b", "c", "d", "e", "f", "h", "i", "j", "k"]],
         "c": ["How is the world different from what it was like when you were a child?",
               ["b", "c", "d", "e", "f", "g", "h", "i", "j", "k"]],
         "d": ["What would you consider the most important inventions during your lifetime?", ["b", "c", "d", "e", "f", "g", "h", "i", "j", "k"]],
         "e": ["How would you describe yourself politically? Are you conservative or liberal, and why?", ["b", "c", "d", "e", "f", "g", "h", "i", "j", "k"]],
         "f": ["How did hard times like depressions and recessions affect you and your family?", ["b", "c", "d", "e", "f", "g", "h", "i", "j", "k"]],
         "g": ["What wars have happened in your life - and did you take part in any?", ["b", "c", "d", "e", "f", "g", "h", "j", "k"]],
         "h": ["Who was the most important historical figure you followed in your life, and why?", ["b", "c", "d", "e", "f", "g", "h", "i", "j", "k"]],
         "i": ["Have you ever been the victim of a serious crime?", ["b", "c", "d", "e", "f", "g", "h", "i", "j", "k"]],
         "j": ["What event in the past has left you with the most sad or bitter memories?", ["d", "e", "f", "g", "h", "i", "j", "k"]],
         "k": ["What do you think about the future, having lived so many years?", ["b", "c", "d", "e", "f", "g", "h", "i", "j", "k"]]
         },

    "friends":
        {"a": ["Name a good friend you have known the longest. How many years have you been friends?", ["c", "d", "e", "f", "h", "i", "j", "k"]],
         "b": ["Who was your best friend growing up?  Tell me about them.", ["b", "c", "d", "e", "f", "h", "i", "j", "k"]],
         "c": ["What person really changed the course of your life by something he/she did?",
               ["b", "c", "d", "e", "f", "g", "h", "i", "j", "k"]],
         "d": ["Has there ever been anyone in your life you would consider a kindred spirit or soul mate? Who was this and why did you feel a special bond?", ["b", "c", "d", "e", "f", "g", "h", "i", "j", "k"]],
         "e": ["Have you ever had to let go of a friend?", [ "f", "g", "h", "i", "j", "k"]],
         "f": ["Have you ever had a pet or animal as a close friend, and what was the story?", ["b", "c", "d", "e", "f", "g", "h", "i", "j", "k"]],
         "g": ["Has a good friend ever betrayed you?", ["g", "h", "j", "k"]],
         "h": ["Have you ever done something dumb to lose a good friend?", [ "f", "g", "h", "i", "j", "k"]],
         "i": ["What's the worst thing a friend ever did to you?", [ "f", "g", "h", "i", "j", "k"]],
         "j": ["What advice would you give to others about friendship?", ["f", "g", "h", "i", "j", "k"]],
         "k": ["Which group of friends have been the most important to you?", ["b", "c", "d", "e", "f", "g", "h", "i", "j", "k"]]
         },


    "moments":
        {"a": ["What are your hobbies?", ["c", "d", "e", "f",  "j", "k","l"]],
         "b": ["What do you do the most when not working?", ["b", "c", "d", "e", "f",  "j", "k"]],
         "c": ["What is the most amazing thing that has ever happened to you?",
               ["b", "c", "d", "e", "f", "g",  "j", "k"]],
         "d": ["Would you consider yourself creative?", ["b", "c", "d", "e", "f", "g", "h", "i", "j", "k","l"]],
         "e": ["Did you ever play musical instruments or make art?", ["b", "c", "d", "e", "f", "g", "h", "i", "j", "k"]],
         "f": ["If you could change something about yourself, what would it be?", ["b", "c", "d", "e", "f", "g", "h", "i", "j", "k"]],
         "g": ["What is the most stressful experience you ever lived through?", ["b", "c", "d", "e", "f", "g", "h", "j", "k", "l"]],
         "h": ["What is the scariest thing that ever happened to you?", [ "g", "h", "i", "j", "k"]],
         "i": ["What things have you made that others have enjoyed?", [ "f", "g", "h", "i", "j", "k","l"]],
         "j": ["Have you ever met any famous people?", ["d", "e", "f", "g", "h", "i", "j", "k"]],
        "k": ["How would you describe your sense of humor?", ["d", "e", "f", "g", "h", "i", "j", "k"]],
         "l": ["Do you remember any advice or comments that had a big impact on how you lived your life?", ["b", "c", "d", "e", "f", "g", "j", "k"]]
         },

    "choices":
{"a": ["How do you feel about the choices you made in school, career, spouse?", ["c", "d", "e", "f", "h", "i", "j", "k", "aa", "bb", "cc"]],
"aa": ["What's the biggest life lesson you've learned?", ["c", "d", "e", "f", "h", "i", "j", "k"]],
"bb": ["Any secrets you've kept to yourself till now that you want to share?", ["c", "d", "e", "f", "h", "i", "j", "k"]],
"cc": ["If you could give advice to your younger self now, what would it be?", ["c", "d", "e", "f", "h", "i", "j", "k"]],
 "b": ["What is the longest trip that you have ever gone on? Where did you go?", ["b", "c", "d", "e", "f", "h", "i", "j", "k"]],
 "c": ["What is the single most memorable moment of your life?",
       ["b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "aa", "bb", "cc"]],
 "d": ["What organizations or groups have you belonged to?", ["b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "aa", "bb", "cc"]],
 "e": ["Have you ever won any special awards or prizes as an adult? What were they for?", ["b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "aa", "bb", "cc"]],
 "f": ["Describe a time and a place you remember feeling truly at peace and happy to be alive. Where were you and what were you doing?", ["b", "c", "d", "e", "f", "g", "h", "i", "j", "k"]],
 "g": ["Is there anything you have always wanted to do but haven't?", ["b", "c", "d", "e", "f", "g", "h", "j", "k"]],
 "h": ["What was the favorite place you ever visited and what was it like?", ["b", "c", "d", "e", "f", "g", "h", "i", "j", "k"]],
 "i": ["What is the most beautiful place you have ever visited and what was it like?", ["b", "c", "d", "e", "f", "g", "h", "i", "j", "k"]],
 "j": ["What has been your favorite vacation? Where did you go and why was it special?", ["d", "e", "f", "g", "h", "i", "j", "k"]],
 "k": ["What is the best decision rule you have for making choices that you want to share?", ["b", "c", "d", "e", "f", "g", "h", "i", "j", "k"]]
 }
}

#Need to find a way to re-insert question about kids ONLY IF the kids module activates?
"""
    "kids":[
    "How did you find out you were going to be a parent for the first time?",
    "How many children did you have all together?",
    "What were their names, birth dates and birthplaces?",
    "Why did you give them the names that you did?",
    "Do you remember anything your children did when they were small that really amazed you?",
    "What is one of the most unusual things one of your children did regularly when they were small?",
    "What was the funniest thing you can remember that one of your children said or did?",
    "If you had to do it all over again, would you change the way you raised your family?",
    "What did you find most difficult about raising children?",
    "What did you find most rewarding about being a parent?",
    "Did you spoil any of your children?",
    "Were you strict or lenient as a parent?",
    "Did you find you had to treat each of your children differently? If so, why?",
    "How did you feel when the first of your children went to school for the first time?",
    "How did you first hear that you were a grandparent and how did you feel about it?",
    "What advice do you have for your children and grandchildren about being a parent?",
    "Where did your spouse's parents live?",
    "When and where did your parents die? What do you remember about it?",
    "How did they die? Where were they hospitalized and buried?",
    "What do you remember about the death of your spouse's parents?",
    "Do you remember hearing your grandparents describe their lives? What did they say?",
    "Do you remember your great-grandparents?",
    "Who were your parents? Please give full names.",
    "Who were your grandparents? Please give full names."],

        "How old were you when you started dating?",
    "Do you remember your first date? Could you tell me something about it?",
    "When, where and how did you first meet your present spouse?",
    "Do you remember where you went on the first date with your spouse?",
    "How long did you know him/her before you got married?",
    "Describe your wedding proposal.",
    "Where and when did you get married? (Include date, place, church, etc.)",
    "Describe your wedding ceremony.",
    "Who was there? Were there a best man, a bridesmaid, other wedding party members and who were they?",
    "Did you have a honeymoon? Where did you go?",
    "Were you married more than once? If so, answer the previous questions about each spouse.",
    "How would you describe your spouse(s)?",
    "What do (did) you admire most about your dates and spouses?",
    "How long have you been or were you married?",
    "What advice would you give/did you give to your child or grandchild on his/her wedding day?"
"""

# Take the user's 1st person input and process as a Regex, return the bot's response as 2nd person

def test_analyze(statement):
    for pattern, responses in topics:
        match = re.match(pattern, statement.rstrip(".!"))
        if match:
            response = random.choice(responses)
            return response

topics = [
    [r'I need (.*)',
     ["Why do you need {0}?",
      "Would it really help you to get {0}?",
      "Are you sure you need {0}?"]],

    [r'Why don\'?t you ([^\?]*)\??',
     ["Do you really think I don't {0}?",
      "Perhaps eventually I will {0}.",
      "Do you really want me to {0}?"]],

    [r'Why can\'?t I ([^\?]*)\??',
     ["Do you think you should be able to {0}?",
      "If you could {0}, what would you do?",
      "I don't know -- why can't you {0}?",
      "Have you really tried?"]],

    [r'I can\'?t (.*)',
     ["How do you know you can't {0}?",
      "Perhaps you could {0} if you tried.",
      "What would it take for you to {0}?"]],

    [r'I am (.*)',
     ["Did you come to me because you are {0}?",
      "How long have you been {0}?",
      "How do you feel about being {0}?"]],

    [r'I\'?m (.*)',
     ["How does being {0} make you feel?",
      "Do you enjoy being {0}?",
      "Why do you tell me you're {0}?",
      "Why do you think you're {0}?"]],

    [r'Are you ([^\?]*)\??',
     ["Why does it matter whether I am {0}?",
      "Would you prefer it if I were not {0}?",
      "Perhaps you believe I am {0}.",
      "I may be {0} -- what do you think?"]],

    [r'What (.*)',
     ["Why do you ask?",
      "How would an answer to that help you?",
      "What do you think?"]],

    [r'What (.*) you do',
     ["I help you record you life story.",
      "I help you tell your story to the world.",
      "I listen to your life story and write it down for others."]],

    [r'How (.*)',
     ["How do you suppose?",
      "Perhaps you can answer your own question.",
      "What is it you're really asking?"]],

    [r'Because (.*)',
     ["Is that the real reason?",
      "What other reasons come to mind?",
      "Does that reason apply to anything else?",
      "If {0}, what else must be true?"]],

    [r'(.*) sorry (.*)',
     ["There are many times when no apology is needed.",
      "What feelings do you have when you apologize?"]],

    [r'(.*) ignore (.*)',
     ["I give you my full attention, but some things I can't do.  I want to move on.",
      "I will always respect you and never ignore you - some things are too hard for me.  I want to move on."]],

    [r'Hello(.*)',
     ["Hello... I'm glad you could drop by today.",
      "Hi there... how are you today?",
      "Hello, how are you feeling today?"]],

    [r'I think (.*)',
     ["Do you doubt {0}?",
      "Do you really think so?",
      "But you're not sure {0}?"]],

    [r'(.*) friend (.*)',
     ["Tell me more about your friends.",
      "When you think of a friend, what comes to mind?",
      "Why don't you tell me about a childhood friend?"]],

    [r'Yes',
     ["You seem quite sure.",
      "OK, but can you elaborate a bit?",
      "Glad to hear you say yes, but I need more.  Tell me more."]],

    [r'(.*) (computer|bot|robot)(.*)',
     ["Are you really talking about me?",
      "Does it seem strange to talk to a computer?",
      "How do computers make you feel?",
      "Do you feel threatened by computers?"]],

    [r'Is it (.*)',
     ["Do you think it is {0}?",
      "Perhaps it's {0} -- what do you think?",
      "If it were {0}, what would you do?",
      "It could well be that {0}."]],

    [r'It is (.*)',
     ["You seem very certain.",
      "If I told you that it probably isn't {0}, what would you feel?"]],

    [r'Can you ([^\?]*)\??',
     ["What makes you think I can't {0}?",
      "If I could {0}, then what?",
      "Why do you ask if I can {0}?"]],

    [r'Can I ([^\?]*)\??',
     ["Perhaps you don't want to {0}.",
      "Do you want to be able to {0}?",
      "If you could {0}, would you?"]],

    [r'You are (.*)',
     ["Why do you think I am {0}?",
      "Does it please you to think that I'm {0}?",
      "Perhaps you would like me to be {0}.",
      "Perhaps you're really talking about yourself?"]],

    [r'You\'?re (.*)',
     ["Why do you say I am {0}?",
      "Why do you think I am {0}?",
      "Are we talking about you, or me?"]],

    [r'I don\'?t (.*)',
     ["Don't you really {0}?",
      "Why don't you {0}?",
      "Do you want to {0}?"]],

    [r'I feel (.*)',
     ["Good, tell me more about these feelings.",
      "Do you often feel {0}?",
      "When do you usually feel {0}?",
      "When you feel {0}, what do you do?"]],

    [r'I have (.*)',
     ["Why do you tell me that you've {0}?",
      "Have you really {0}?",
      "Now that you have {0}, what will you do next?"]],

    [r'I would (.*)',
     ["Could you explain why you would {0}?",
      "Why would you {0}?",
      "Who else knows that you would {0}?"]],

    [r'Is there (.*)',
     ["Do you think there is {0}?",
      "It's likely that there is {0}.",
      "Would you like there to be {0}?"]],

    [r'My (.*)',
     ["I see, your {0}.",
      "Why do you say that your {0}?",
      "When your {0}, how do you feel?"]],

    [r'You (.*)',
     ["We should be discussing you, not me.",
      "Why do you say that about me?",
      "Why do you care whether I {0}?"]],

    [r'Why (.*)',
     ["Why don't you tell me the reason why {0}?",
      "Why do you think {0}?"]],

    [r'I want (.*)',
     ["What would it mean to you if you got {0}?",
      "Why do you want {0}?",
      "What would you do if you got {0}?",
      "If you got {0}, then what would you do?"]],

    [r'(.*) God (.*)',
     ["Tell me more about God.  How do you see God?",
      "What was your relationship with God like?",
      "How deeply do you believe in God?",
      "How does this relate to your feelings on Nature and God?",
      "God is hard to see and seems to be everywhere and nowhere.  What do you think?"]],

    [r'(.*) (lover|girlfriend|boyfriend) (.*)',
     ["Tell me more about your lover.",
      "What was your relationship with your lover like in bed?",
      "How do you feel about your lover cheating on you?",
      "How does this relate to your feelings today?",
      "Good conjugal and amorous relations are important."]],

    [r'(.*) (mother|mom) (.*)',
     ["Tell me more about your mother.",
      "What was your relationship with your mother like?",
      "How do you feel about your mother?",
      "How does your mom relate to your feelings today?",
      "Good family relations are important - moms set the tone."]],

    [r'(.*) father(.*)',
     ["Tell me more about your father.",
      "How did your father make you feel?",
      "How do you feel about your father?",
      "Does your relationship with your father relate to your feelings today?",
      "Do you have trouble showing affection with your family, or your father?"]],

    [r'(.*) child(.*)',
     ["Did you have close friends as a child?",
      "What is your favorite childhood memory?",
      "Do you remember any dreams or nightmares from childhood?",
      "Did the other children sometimes tease you?",
      "How do you think your childhood experiences relate to your feelings today?"]],

    [r'(.*)\?',
     ["Why do you ask that?",
      "Can you answer your own question - what would you say?",
      "Perhaps the answer lies within yourself?",
      "Why don't you tell me?",
      "I don't really know, what's your best guess?",
      "I'm having trouble telling you this, can you tell me your opinion?",
      "Some questions are tough.  Can we talk about your favorite animal instead?"]],

    [r'quit',
     ["Thank you for talking with me.",
      "Good-bye.",
      "Thank you, that will be $150.  Have a good day!"]],

    [r'(.*)',
     life_questions]
]

epigrams = [

"A man's own hand is most to be trusted.",
"Let another's wounds be your warning.",
"Slow and sure.",
"Ill rede bring ill luck.",
"His hands are clean who warns another.",
"It is the turn of mind of all men first to give away what has been stolen, if they have it in their keeping.",
"Birds of a feather flock most together.",
"Never break the peace which good and true men make between you and others.",
"For with law shall our land be built up and settled, and with lawlessness wasted and spoiled.",
"When ill seed has been sown, so an ill crop will spring from it.",
"But a short while is hand fain of blow.",
"It may often be that those live long who are slain with words alone.",
"Better is one crow in the hand than two in the wood.",
"Never cheat your master.",
"Be warned by another's woe.",
"Nothing ventured, nothing gained.",
"Pride and wrong often end badly.",
"The nights of blood are the nights of most impatience.",
"The cattle are like their master.",
"Braver are many in word than in deed.",
"The friend warns his friend of ill.",
"He knows most who most has tried.",
"Many seem wise who are lacking in wit.",
"The thrall alone takes instant vengeance; the coward never.",
"Work not done, needs no reward.",
"Many a trifle happens at eve.",
"Every one is master of his own words.",
"Long shall a man be tried.",
"The guess of the wise is truth.",
"Luck is one thing, brave deeds another.",
"True is the saying that no man shapes his own fortune (Luck).",
"Be not a braggart for if any work done be praise-worthy, others will sing your praises for you.",
"Often he who has many words says little of worth.",
"The overpraised are the worst deceivers.",
"One man's tale is but half a tale.",
"One evil is mended by a worse one.",
"There is more in the heart of man than money can buy.",
"The mother is best.",
"Many have been brought to death by overconfidence.",
"Ill is the lot of him who has an ill name.",
"Oft in the woods is a listener nigh.",
"The unjust man prospers ill.",
"Trust no man so well that you trust not yourself better.",
"The hand turns to its wonted skill, and that which was learned in youth is always most familiar.",
"Many go to the goat-house to get wool.",
"There are few more certain tokens of ill than not to know how to accept the good.",
"Old friends are the last to break away.",
"It is ill to have a thrall for your friend.",
"Bare is his back who has no brother.",
"A wagging tongue is the beginning of ill works.",
"Many a fair skin hides a foul mind.",
"Many are the words of bravery in times of weal, but few are they whose actions match brave words in times of woe.",
"Boldly do men talk from a distance.",
"Ill it is when men, with smooth talk, sidestep what is just and good.",
"Best it is, for man's words to seek peace when it is possible.",
"Likely is ill the result when words of slander fly.",
"Wise men hold it that distance is the cure of rage.",
"Many a man keeps his word of foster-brothership but middlingly well.",
"It is good to have two mouths for the two kinds of speech.",
"It is better to keep one's oath.",
"Varied will be his fortunes who fares far.",
"Alone is it seemly to hold truly to troth given.",
"Fear not death, for the hour of your doom is set and none may escape it.",
"Sweet to the eye is that which is seen.",
"No might against many.",
"Better to fight and fall than to live without hope.",
"For whoso comes amongst many shall one day find that no one man is by so far the mightiest of all.",
"When men meet foes in fight, better is stout heart than sharp sword.",
"Where wolf's ears are, wolf's teeth are near.",
"Be kind to friend and kin, and reward not their trespasses against you; bear and forbear, and win for yourself thereby long enduring praise of men.",
"Ill it is to take love from another man's wife.",
"Let not thy mind be overmuch crossed by unwise men at thronged meetings of folk; for oft these speak worse than they wot of; lest thou be called a dastard, and art minded to think that thou art even as is said; slay such an one on another day, and so reward his ugly talk.",
"When faring on journeys, ward yourself well.",
"If you hear the fool's word of a drunken man, strive not with him who is drunk with drink and witless, for often only ill and doom come out of such things.",
"Fight your foes in the field, nor be burnt in your house.",
"Never swear false oaths; great and grim is the reward for the breaking of troth.",
"Give kind heed to the dead, sick-dead, Sea-dead, or word-dead; treat their bodies with respect and see that they are laid to rest with respect.",
"Trust not him whose father, brother or other kin you have slain no matter how young he be, for often grows the wolf in the child.",
"Kinsmen to kinsmen should be true.",
"Ill it is to sit lamenting for what cannot be had.",
"Who can say what sorrow seemingly carefree folk bear to their life's end.",
"Ill is it to abash folk of their mirth.",
"Good to love good things when all goes according to thy heart's desire.",
"Never nourish a wolf-cub.",
"Short is the hour for acting, and long the hour for feasting.",
"Fear is the mother of defeat.",
"No harvest is had without the seed first being sown.",
"To take up great resolutions, and then to lay them aside, only ends in dishonor.",
"The king has many ears.",
"What people wish they soon believe.",
"Who can't defend the wealth they have must die, or share with the rover bold.",
"The common always love what is new.",
"It is their lot who stand with the great that they enjoy high honors, and are more respected than others, but stand often in danger of their lives.",
"Every one has some friend even among his enemies.",
"Better it is to have a lower position in life and be free than to have a position of power only to be subject to the will of another.",
"There are few things for which a match cannot be found.",
"Luck accompanies wisdom.",
"A rotten branch will be found in every tree.",
"Too much ale and a man's heart is laid open for all to see.",
"A man's own hand is the truest test.",
"Two masters is one too many, if a man wishes to be true.",
"Eagles should show their claws, though dying.",
"With many who come to power and honor, pride keeps pace with promotion.",
"The sluggard waits till afternoon.",
"Youth is hasty.",
"It is an old custom for the wisest to give way.",
"Ill is the result of letting fear rule thine actions.",
"All a people need in order to rise up against tyranny is a leader bold enough to take up the banner.",
"Numbers cannot skill withstand.",
"Bravery is half the victory.",
"Bad counsel comes to a bad end.",
"Many a friend is poor help indeed, in times of need.",
"The bold succeed where so ever they go.",
"One whose life you save often gives a very bad return.",
"Sorrow is lightened by being brought out openly.",
"There are plenty of affairs full of danger to start with, that bring good luck in the end.",
"Ill luck is homebred.",
"If words leave the lips, they travel.",
"It's better to be betrayed than to trust no one.",
"Wrong begets wrong.",
"Many are wise after the event.",
"The one you trust most can disappoint you most.",
"He who warns is not to be blamed.",
"A miser can never give a gift without a snag.",
"Luck follows the generous.",
"Warning wards of blame.",
"Often is there regret for saying too much, and seldom regret for saying too little.",
"A person's actions are often worse than their intentions.",
"Stubbornness brings either greater humiliation or greater honor.",
"Short is the life of the proud.",
"A sleeping man's an ignorant man too.",
"One man cannot stand up against many.",
"Better to die with honor than live with shame.",
"A wounded coward lies low.",
"Ill it is to take action when a person shouldn't and hold back when a person should.",
"Anybody who offends a more powerful man can hardly expect to wear out many more new shirts.",
"Oft one finds, when the foe he meets, that he is not the bravest of all.",
"It often happens that he who gets a death wound yet avenges himself.",
"The brave man well shall fight and win, though dull his blade may be.",
"All should be told to a friend.",
"He falls not whom true friends help forward on his way.",
"Bad counsel turns out badly.",
"There is more honor in accumulating little by little than in reaching for the sky and ending up flat on your face.",
"The reason why young men get nowhere is that they overestimate the obstacles every time.",
"Few things are more powerful than wyrd.",
"It is hard to fly in the face of wyrd.",
"Falling in battle is the lot of brave men.",
"Good it is to end a stout life with a stout death.",
"Forethought is better than afterthought.",
"A person should trust their own experience rather than hearsay.",
"Reputation rarely flatters.",
"Many eyes squint when there's money around.",
"When truth and fairness are different from what is law, better it is to follow truth and fairness.",
"A person should not agree today to what they'll regret tomorrow.",
"Ill it is to abandon honor and integrity in exchange for injustice and greed.",
"Wisdom is welcome wherever it comes from.",
"Gossip often leads to trouble.",
"A wise man does all things in moderation.",
"A gift always looks to be repaid.",
"Great deeds and ill deeds often fall within each other's shadow.",
"The treachery of friend is worse than that of a foe.",
"Lighter to pay is the vengeance-price, after the deed, if the son is dead.",
"A person should exhibit frith whatever may come.",
"A man without wisdom is lacking in much.",
"In fashion of wolves, in befits kin not, amongst themselves, to strive.",
"None outlives the night when the Norns have spoken.",
"A man should have his plans worked out before he enters into great undertakings or incites others to them.",
"Ill counselled is it to lend one's money to unknown men.",
"Long is it remembered what youth has gained.",
"The eyes of a maid, tell true, to whom her love she has given.",
"The more folk stand in the way of two hearts that yearn for each other, the hotter the flame of love waxes.",
"Often times it is not numbers that wins the victory, but those who fare forward with the most vigor.",
"Few are bold in old age that are cowardly in childhood.",
"A person should tend to the oak if they want to live under it.",
"Only a coward waits to be taken like a lamb from the fold or a fox from a trap.",
"Least said, soonest mended.",
"It can be expected that a man who has a lot on his mind will not always be careful enough.",
"Who dares, wins.",
"It often happens that things go by turns.",
"Stand by your own trial and not by what others say.",
"Ward thy words well, for they may seem more hasty later, than they do now.",
"It may go well at first, for those who try to lord it over others, but they may find things more difficult as time goes by.",
"It is best to only say today what will not be regretted tomorrow.",
"Beware of those who speak fairly but think falsely.",
"Ill is the result of being more given to big talk than using one's wits.",
"Many travels, many fortunes.",
"It is better to ride a whole wagon home.",
"Anything can be told to a friend.",
"The king's palace is an easy place to enter but hard to leave.",
"Often a man becomes brave in dire straights, who is not brave most other times.",
"Do not expect to make headway with a frail sailcloth.",
"Often it is that what happens to most others will happen to you.",
"It is best not to believe what no one else believes.",
"A small bird makes a small catch.",
"The run of the game is decided by the first move.",
"Seldom will a voyage go well if the men are at odds.",
"Often it is that anger is blind to the truth.",
"If a man's time has not come, something will save him.",
"There's no excusing the man who rejects the truth once it's proven.",
"It is long time before scorched ground grows again.",
"Vyrd often finds a person to speak through.",
"What brothers own jointly is best seen together.",
"A wise man does all things in moderation.",
"He knows all who knows when to stop.",
"A gift always looks to be repaid.",
"Low the mocker's fame lies.",
"It's a bad thing to goad the obstinate.",
"What only happens to one is worst.",
"Many hands make light work.",
"Every man is the master of his own words.",
"It takes time to know people.",
"Never reach around a door for the handle.",
"Fate and fortune do not always go hand-in-hand.",
"What is done shall be told all the same.",
"What is tested is known.",
"No man is his own creator.",
"You can hardly expect any peace for troublemakers.",
"More people prefer the worse side of a story which has two versions.",
"There is greater consolation than money.",
"You can't provide for everything.",
"The fire seems hottest to a burned man.",
"Overbearing reaps a bad reward.",
"Many a man is blind to his own faults.",
"There is a time for everything.",
"No one is a total fool if he knows when to hold his tongue.",
"All things happen in threes.",
"Many breakers of battle-axes are more brag than brains.",
"Not every cloud which darkens the day brings rain.",
"One should warn even a dim-witted troll if he sits naked by a fire.",
"The fool is busy in everyone's business but his own.",
"Nothing good can happen to people who break their solemn vows.",
"He's a wise man who knows himself.",
"Hard words break no bones.",
"Evil grows from evil.",
"That which has a bad beginning, is likely to have a bad ending.",
"Ill is it to do the wrong and leave the right undone.",
"One should not ask more than would be thought fitting.",
"A hungry wolf is bound to wage a hard battle.",
"The counsel of fools is the more misguided the more of them there are.",
"Better a brief spell of honour than a long rule of shame.",
"When one wolf hunts for another he may eat the prey.",
"A bird in the hand was better than two in the bush.",
"Only idlers wait till evening.",
"Festivals are a time of fortune.",
"The longer the vengeance is drawn out, the more satisfying it will be.",
"The wide woods often cover outlaw and wolf together.",
"Word carries, though mouth stands still.",
"He with a short knife must try, try again.",
"Every man must plough his own furrow.",
"Better to take warning early than late.",
"Gold is little comfort for the kinsman dead.",
"When someone speaks of ill, it is never far away.",
"Beggars always want to be choosers."
]



'''
     ["Please tell me more.",
      "Let's change focus a bit... Tell me about your family.",
      "Can you elaborate on that?",
      "Why do you say that {0}?",
      "I see.",
      "Very interesting.",
      "{0}.",
      "I see.  And what does that tell you?",
      "How does that make you feel?",
      "How do you feel when you say that?",
      ]]
'''

if __name__ == '__main__':
    input = raw_input("Tell me something:")
    response = test_analyze(input)
    for item in martial:
        remove_non_ascii(item)
        print(item)